"""The conformance suite.

Every Licencly SDK runs this same file, which is what keeps four independent
implementations from drifting apart. A vendor switching from Go to Python must
get identical answers.

``tests/data/vectors.json`` is generated by the server repo. Do not edit it here.

Written against stdlib unittest so it runs with `python -m unittest` on a bare
interpreter; pytest picks it up unchanged.
"""

from __future__ import annotations

import json
import unittest
from datetime import datetime, timezone
from pathlib import Path

from licencly import (
    LicenseFileError,
    evaluate,
    is_tampering,
    public_key_from_base64,
    verify_with_keys,
)

VECTORS = json.loads((Path(__file__).parent / "data" / "vectors.json").read_text())["vectors"]


def keys_for(vector):
    return {kid: public_key_from_base64(k) for kid, k in vector["public_keys"].items()}


def decide(vector):
    now = datetime.fromtimestamp(vector["now"], tz=timezone.utc)

    claims, error = None, None
    try:
        claims = verify_with_keys(vector["file"], keys_for(vector))
    except LicenseFileError as exc:
        error = exc

    return evaluate(claims, error, now, vector["fingerprint"], False), now


class ConformanceTest(unittest.TestCase):
    def test_vectors_are_present(self):
        self.assertGreater(len(VECTORS), 0, "vectors.json is empty")

    def test_every_vector(self):
        for vector in VECTORS:
            with self.subTest(vector=vector["name"]):
                decision, _ = decide(vector)

                self.assertEqual(
                    decision.outcome.value, vector["expect"], vector["description"]
                )

                if vector["expect"] != "valid":
                    continue

                self.assertEqual(
                    decision.needs_revalidation,
                    vector["needs_revalidation"],
                    "needs_revalidation",
                )
                self.assertEqual(
                    decision.maintenance_active,
                    vector["maintenance_active"],
                    "maintenance_active",
                )

    def test_tampering_is_not_retryable(self):
        """A client that retries a forged file hides an attack behind what looks
        like a flaky network."""
        for vector in (v for v in VECTORS if v["expect"] == "invalid"):
            with self.subTest(vector=vector["name"]):
                with self.assertRaises(LicenseFileError) as caught:
                    verify_with_keys(vector["file"], keys_for(vector))

                self.assertTrue(
                    is_tampering(caught.exception),
                    "not reported as tampering, so callers will retry",
                )

    def test_vectors_cover_every_outcome(self):
        seen = {v["expect"] for v in VECTORS}

        for outcome in ("valid", "invalid", "not_active", "expired", "wrong_machine", "stale"):
            self.assertIn(outcome, seen, f"no vector expects {outcome}")


if __name__ == "__main__":
    unittest.main()
